# Generated by Django 5.2.7 on 2025-11-03 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_veterinaria',
            name='motivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.servicio'),
        ),
    ]
