# Generated by Django 5.2.7 on 2025-11-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cita_veterinaria_motivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita_veterinaria',
            old_name='estatus',
            new_name='estatus_cita',
        ),
        migrations.RenameField(
            model_name='cita_veterinaria',
            old_name='motivo',
            new_name='servicio',
        ),
    ]
