# Generated by Django 5.2.8 on 2025-11-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_estatus_cita_veterinaria_estatus_cita_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita_veterinaria',
            options={'permissions': [('change_status_only', 'Puede cambiar solo el estatus de la cita.')]},
        ),
    ]
