# Generated by Django 5.2.7 on 2025-11-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cita_veterinaria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita_veterinaria',
            options={'permissions': [('consulta_full_edit', 'Puede cambiar todos los elementos de una cita.')]},
        ),
    ]
